### ISSUE TITLE
Error in Azure Function: No valid combination of account information found.

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/batch-functions-tutorial#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Set up the tutorial as intended and drop one file in the input container.

### Any log messages given by the failure
> `2023-03-08 01:14:07.197
Executing 'Functions.BatchTrigger1' (Reason='New blob detected(LogsAndContainerScan): input/scan01.pdf', Id=39d82eed-9181-416e-a640-d0e093bbff6d)
Information
2023-03-08 01:14:07.197
Trigger Details: MessageId: 6cdd12d8-0c1a-4342-bbd2-10e868f55126, DequeueCount: 1, InsertedOn: 2023-03-08T01:14:07.000+00:00, BlobCreated: 2023-03-08T01:14:00.000+00:00, BlobLastModified: 2023-03-08T01:14:00.000+00:00
Information
2023-03-08 01:14:07.912
Creating job...
Information
2023-03-08 01:14:08.005
No valid combination of account information found.
Error
2023-03-08 01:14:08.006
Executed 'Functions.BatchTrigger1' (Failed, Id=39d82eed-9181-416e-a640-d0e093bbff6d, Duration=822ms)
Error
2023-03-08 01:14:08.008
No valid combination of account information found.`

### Expected/desired behavior
> Funtion runs properly

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful
I've followed the instructions carefully, all my credentials in run.csx appear to be accurate. The only question would be, does my output SAS need to be the URL or the Key?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ghost** [comment]
User error. I had the key for the container in place of the connection string. All is working as intended now. Thanks!

**Comment by Jesson1018** [comment]
> User error. I had the key for the container in place of the connection string. All is working as intended now. Thanks!

Could you please explain more here for reference? Thanks in advance!
